version: 2.1

jobs:
  build-base-image:
    docker:
      - image: cimg/python:3.11.3
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
          docker_layer_caching: false
      - run:
          name: "Build and push image"
          command: |
            PHP_VERSION = "8.2"
            DOCKER_IMAGE_REPO="${DOCKERHUB_USERNAME}/np-php${PHP_VERSION}"
            DOCKER_IMAGE_RELEASE_TAG="${DOCKER_IMAGE_REPO}:${CIRCLE_TAG}"
            DOCKER_IMAGE_LATEST_TAG="${DOCKER_IMAGE_REPO}:latest"

            docker build -t $DOCKER_IMAGE_REPO . -f ./docker/Dockerfile \
                   --build-arg=PHP_VERSION="${PHP_VERSION}"

            docker tag $DOCKER_IMAGE_REPO $DOCKER_IMAGE_RELEASE_TAG
            docker tag $DOCKER_IMAGE_REPO $DOCKER_IMAGE_LATEST_TAG
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKER_IMAGE_RELEASE_TAG
            docker push $DOCKER_IMAGE_LATEST_TAG

workflows:
  build:
    jobs:
      - build-base-image:
          filters:
            tags:
              only: /.+/
            branches:
              only:
                - main
